apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: conote
build:
  artifacts:
    - image: conote-frontend
      context: .
      docker:
        dockerfile: Dockerfile.dev
        target: frontend-dev
    - image: conote-backend
      context: .
      docker:
        dockerfile: Dockerfile.dev
        target: backend-dev
deploy:
  kustomize:
    paths:
      - k8s
    #   - overlays/dev
# profiles:
#   - name: prod
#     deploy:
#       kustomize:
#         paths:
#           - overlays/prod
#   - name: staging
#     deploy:
#       kustomize:
#         paths:
#           - overlays/staging
